USE [BOOKS]
GO

CREATE SCHEMA [Books]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Books].[Autore](
	[AutoreID] [int] NOT NULL,
	[Nome] [varchar](100) NOT NULL,
	[Cognome] [varchar](100) NOT NULL,
	[DataNascita] [date] NOT NULL,
	[LuogoNascita] [varchar](100) NOT NULL,
	[DataMorte] [date] NULL,
	[LuogoMorte] [varchar](100) NULL,
	[InAttivita] [bit] NOT NULL,
 CONSTRAINT [PK_Autore] PRIMARY KEY CLUSTERED 
(
	[AutoreID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Books].[CasaEditrice](
	[CasaEditriceID] [int] NOT NULL,
	[Nome] [varchar](100) NOT NULL,
 CONSTRAINT [PK_CasaEditrice] PRIMARY KEY CLUSTERED 
(
	[CasaEditriceID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Books].[Libro](
	[LibroID] [int] NOT NULL,
	[Titolo] [varchar](100) NOT NULL,
	[AutoreID] [int] NOT NULL,
	[Prezzo] [decimal](10, 5) NOT NULL,
	[BestSeller] [bit] NOT NULL,
	[CasaEditriceID] [int] NOT NULL,
 CONSTRAINT [PK_Libro] PRIMARY KEY CLUSTERED 
(
	[LibroID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
